name: agrosat_alert
description: AgroSat Alert - Monitoramento Agrícola via Satélite

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
